<a href="https://colab.research.google.com/github/Dylonius/electro-modular-boi/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array = np.array(10)

In [3]:
print(array)

10


In [4]:
type(array)

numpy.ndarray

In [5]:
zerodimension = np.array(10)

In [6]:
print(zerodimension)

10


In [8]:
print(zerodimension.ndim)

0


In [10]:
onedimension = np.array([5,15,25,35])
print(onedimension)

[ 5 15 25 35]


In [11]:
print(onedimension.ndim)

1


In [12]:
twodimension = np.array([[15,25,45],[64,22,33]])

In [13]:
print(twodimension)

[[15 25 45]
 [64 22 33]]


In [14]:
print(twodimension.ndim)

2


In [16]:
tensor = np.array([[[15,24,25],[24,25,26]],[[20,15,14],[22,32,35]]])

In [17]:
print(tensor)

[[[15 24 25]
  [24 25 26]]

 [[20 15 14]
  [22 32 35]]]


In [18]:
print(tensor.ndim)

3
