<a href="https://colab.research.google.com/github/Dylonius/electro-modular-boi/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
onedimension = np.array([5,15,25,35])
twodimension = np.array([[15,25,45],[64,22,33]])

In [2]:
onedimension.ndim

1

In [3]:
twodimension.ndim

2

In [7]:
onedimension[1:]

array([15, 25, 35])

In [8]:
onedimension[1:3]

array([15, 25])

In [9]:
onedimension[1:4]

array([15, 25, 35])

In [10]:
print(twodimension)

[[15 25 45]
 [64 22 33]]


In [11]:
twodimension[1,1: ]

array([22, 33])

In [12]:
twodimension[1, 1:3]

array([22, 33])

In [13]:
for element in onedimension:
    print(element)

5
15
25
35


In [14]:
for element in onedimension:
  if element > 10:
    print(element)
  else:
      print("Element is less than 10")

Element is less than 10
15
25
35


In [15]:
for element in onedimension:
  print(element *5)

25
75
125
175


In [16]:
for element in twodimension:
  print(element)

[15 25 45]
[64 22 33]


In [18]:
for element in twodimension:
  print(element +9)


[24 34 54]
[73 31 42]


In [19]:
for element in twodimension:
  print(element *5)

[ 75 125 225]
[320 110 165]
